import { WorkItem } from './works.model';

export const WORKS: WorkItem[] = [
  // {
  //   id: 'portfolio-hub',
  //   titleKey: 'WORKS.PORTFOLIO_HUB.TITLE',
  //   year: '2025',
  //   href: '/',
  //   target: 'same-tab',
  //   coverSrc: '/works/cover-01.svg',
  //   coverAltKey: 'WORKS.PORTFOLIO_HUB.COVER_ALT',
  //   grid: { colSpan: 7, rowSpan: 6 },
  // },
  {
    id: 'app-1',
    titleKey: 'WORKS.APP_1.TITLE',
    descriptionKey: 'WORKS.APP_1.DESCRIPTION',
    href: 'https://darkgrey-octopus-623910.hostingersite.com',
    target: 'new-tab',
    coverSrc: '/works/grave-app.png',
    coverAltKey: 'WORKS.APP_1.COVER_ALT',
    grid: { colSpan: 4, rowSpan: 6 },
  },
  {
    id: 'app-2',
    titleKey: 'WORKS.APP_2.TITLE',
    descriptionKey: 'WORKS.APP_2.DESCRIPTION',
    href: 'https://salmon-fly-255466.hostingersite.com/dashboard',
    target: 'new-tab',
    coverSrc: '/works/app-car-dashboard.svg',
    coverAltKey: 'WORKS.APP_2.COVER_ALT',
    grid: { colSpan: 4, rowSpan: 6 },
  },
  {
    id: 'app-3',
    titleKey: 'WORKS.APP_3.TITLE',
    descriptionKey: 'WORKS.APP_3.DESCRIPTION',
    href: '#',
    target: 'same-tab',
    coverSrc: '/works/cover-04.svg',
    coverAltKey: 'WORKS.APP_3.COVER_ALT',
    grid: { colSpan: 4, rowSpan: 6 },
  },
  {
    id: 'app-4',
    titleKey: 'WORKS.APP_4.TITLE',
    descriptionKey: 'WORKS.APP_4.DESCRIPTION',
    href: '#',
    target: 'same-tab',
    coverSrc: '/works/cover-05.svg',
    coverAltKey: 'WORKS.APP_4.COVER_ALT',
    grid: { colSpan: 4, rowSpan: 6 },
  },
];
