import { WorkItem } from './works.model';

export const WORKS: WorkItem[] = [
  {
    id: 'portfolio-hub',
    title: 'Portfolio Hub (this site)',
    year: '2025',
    href: '/',
    target: 'same-tab',
    coverSrc: '/works/cover-01.svg',
    coverAlt: 'Abstract cover image',
    grid: { colSpan: 7, rowSpan: 6 },
  },
  {
    id: 'app-1',
    title: 'My Web App #1',
    year: '2025',
    href: '#',
    target: 'same-tab',
    coverSrc: '/works/cover-02.svg',
    coverAlt: 'Abstract cover image',
    grid: { colSpan: 5, rowSpan: 6 },
  },
  {
    id: 'app-2',
    title: 'App-car (dashboard)',
    year: '2024',
    href: 'https://salmon-fly-255466.hostingersite.com/dashboard',
    target: 'new-tab',
    coverSrc: '/works/app-car-dashboard.svg',
    coverAlt: 'App-car dashboard preview',
    grid: { colSpan: 4, rowSpan: 5 },
  },
  {
    id: 'app-3',
    title: 'My Web App #3',
    year: '2024',
    href: '#',
    target: 'same-tab',
    coverSrc: '/works/cover-04.svg',
    coverAlt: 'Abstract cover image',
    grid: { colSpan: 4, rowSpan: 5 },
  },
  {
    id: 'app-4',
    title: 'My Web App #4',
    year: '2023',
    href: '#',
    target: 'same-tab',
    coverSrc: '/works/cover-05.svg',
    coverAlt: 'Abstract cover image',
    grid: { colSpan: 4, rowSpan: 5 },
  },
];
